### ISSUE TITLE
Concourse 4.2 ldap authentication problems

### ISSUE THREAD

**Issue by itpick** [concourse/concourse-bosh-deployment#105]
I've been able to create teams and assign ldap users specifically
<fly -t concourse-4 set-team -n team1 --local-user admin --ldap-user user1>

tailing the atc.stdout.log file during ldap user login:
{"timestamp":"1538080212.178583622","source":"atc","message":"atc.dex.event","log_level":1,"data":{"fields":{},"message":"login successful: connector \"ldap\", username=\"user1\", email=\"user1@email.com\", groups=[]","session":"5"}}

But the --ldap-group flag with an ldap group is not working to grant access to any concourse team.  

Can you provide an example manifest patch for ldap configuration?  Or is there problem with ldap still?

**Comment by mylucidreality** [comment]
I have tried a number of configs.  This is my currently running LDAP config.  I have also verified this group is in the search path.  I can also get this to work for individual users.

      ldap_auth:
        group_search_base_dn: OU=Cloud Engineering,OU=Groups,OU=xxx,DC=xxx,DC=xxx,DC=com
        group_search_name_attr: cn

fly -t fog set-team -n fog --ldap-group=PCF-Admins
Team Name: fog

Users:
- none

Groups:
- ldap:pcf-admins

**Comment by itpick** [comment]
> I have tried a number of configs. This is my currently running LDAP config. I have also verified this group is in the search path. I can also get this to work for individual users.
> 
> ```
>   ldap_auth:
>     group_search_base_dn: OU=Cloud Engineering,OU=Groups,OU=xxx,DC=xxx,DC=xxx,DC=com
>     group_search_name_attr: cn
> ```
> fly -t fog set-team -n fog --ldap-group=PCF-Admins
> Team Name: fog
> 
> Users:
> 
> * none
> 
> Groups:
> 
> * ldap:pcf-admins

is this a manifest-patch.yml or where do you have this configured?

**Comment by mylucidreality** [comment]
This is set in the deployment manifest
https://bosh.io/jobs/atc?source=github.com/concourse/concourse&version=4.2.1#p%3dldap_auth.group_search_base_dn

**Comment by itpick** [comment]
@mylucidreality 
I've configured the concourse-bosh-deployment/cluster/concourse.yml file correctly or at least according to documentation.  I'm not deploying the lite method.  Again, able to authenticate with users but not through groups.  And I do no see any error messages in the log indicating that groups are/aren't working.

what I'm using:
```
ldap_auth:
    host: <server>:389
    bind_dn: CN=<path of bind user>
    bind_pw: <password>
    insecure_no_ssl: true
    start_tls: false
    user_search_filter: objectClass=person
    user_search_base_dn: <ou location here>
    user_search_username: sAMAccountName
    user_search_scope: sub
    user_search_id_attr: sAMAccountName
    user_search_email_attr: mail
    user_search_name_attr: name
    group_search_base_dn: <ou location here>
    group_search_filter: objectClass=group
    group_search_scope: sub
    group_search_group_attr: member
    group_search_name_attr: cn
```

**Comment by itpick** [comment]
@mylucidreality "I can also get this to work for individual users."  YOu can get both users and groups working at the same time correct?

**Comment by marginquack** [comment]
I think you need group_search_user_attr in there too. For my setup it was distinguishedName. Dex docs have uid in their example. It should just be what user attribute the member list is made up of

**Comment by itpick** [comment]
Finally resolved for MSAD config.  Example:
```
ldap_auth:
        host: server...:389
        bind_dn: CN=bind user....
        bind_pw: password....
        insecure_no_ssl: true
        start_tls: false
        user_search_base_dn: OU=...
        user_search_username: sAMAccountName
        user_search_scope: sub
        user_search_id_attr: sAMAccountName
        user_search_email_attr: mail
        user_search_name_attr: name
        group_search_base_dn: OU=...
        group_search_scope: sub
        group_search_group_attr: member
        group_search_name_attr: cn
        group_search_user_attr: distinguishedName

```
