### ISSUE TITLE
Cluster - Vault AppRole Parameter

### ISSUE THREAD

**Issue by akamalov** [concourse/concourse-bosh-deployment#124]
Greetings,

Wondering, does current ```concourse-bosh-deployment```,  cluster release support the following parameters:

```
CONCOURSE_VAULT_AUTH_BACKEND="approle"
CONCOURSE_VAULT_AUTH_PARAM="role_id=...""
```

I believe, ```CONCOURSE_VAULT_CLIENT_TOKEN``` is  ```((concourse_vault_token))```. I am using ```approle``` and wondering is it possible to pass ```approle``` parameter to my Concourse deployment.

Thank you!!

**Comment by akamalov** [comment]
Answering my own question. Modify your ```operations/vault.yml``` file to include the following parameters:

```
- type: replace
  path: /instance_groups/name=web/jobs/name=atc/properties/vault?
  value:
    path_prefix: ((concourse_vault_mount))
    url: ((vault_url))
    auth:
      client_token: ((concourse_vault_token))
      backend: ((concourse_backend))
      params:
         role_id: ((concourse_role_id))
         secret_id: ((concourse_secret_id))
```
Consequently, update your vars.yml file to provide values required above. Then, you should be set :)
