### ISSUE TITLE
versions file assumes access to bosh.io, provide an operations file that _forces_ offline mode

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse-bosh-deployment#200]
I'd like to provide a operations files that modifies the `releases` to not contain the url portion.
When using this repo in offline environments, if the bosh releases are not there then director tries to download.
Let's avoid that step, because it can add another layer of debugging for some.

It would probably look like:

```yaml
- type: remove
  path: /releases/name=concourse/url
# etc....
```

This will help us in our work for faster debugging in offline envs.
