### ISSUE TITLE
uaa requires the disabling of postgres TLS to be used correctly

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse-bosh-deployment#202]
We had to add custom ops file for UAA to be able to connect to the same postgres instance that is allocated for Concourse via `cluster`.

```yaml
- type: replace
  path: /instance_groups/name=web/jobs/name=uaa/properties/uaadb?/tls
  value: disabled
```

Options:
1. Fix UAA ops file so it uses TLS.
2. Always disable it.
