### ISSUE TITLE
uaa requires larger canary watch

### ISSUE THREAD

**Issue by jtarchie** [concourse/concourse-bosh-deployment#203]
When we deployed UAA (and therefor Credhub), we had to set the canary timeout to a larger value.

```yaml
- type: replace
  path: /instance_groups/name=web/update?
  value:
    update_watch_time: 1000-150000
    canary_watch_time: 1000-150000
```

Options:
1. update the main concourse cluster bosh deployment with these values
2. only use it when the UAA opsfile is provided
