### ISSUE TITLE
Allow variable for azs

### ISSUE THREAD

**Issue by mikexuu** [concourse/concourse-bosh-deployment#33]
Currently the manifest hardcodes the `azs` property to `[z1]`, it would be nice to provide this as a variable.

**Comment by patrickhuber** [comment]
This can be done with an ops file.

```bash
mkdir ops-files
vi az-as-variable.yml
```

```yml
---
- type: replace
  path: /instance_groups/name=web/azs
  value: [((az_name))]
- type: replace
  path: /instance_groups/name=db/azs
  value: [((az_name))]
- type: replace
  path: /instance_groups/name=worker/azs
  value: [((az_name))]
```

```bash
bosh deploy -d concourse \
         /path/to/concourse/repo/github.com/concourse/concourse-deployment/cluster/concourse.yml \
         -l /path/to/concourse/repo/github.com/concourse/concourse-deployment/version.yml \
         -o ops-files/az-as-variable.yml \
         -v az_name=z1
```

Perhaps this can be added to the ops file listings?
