### ISSUE TITLE
add credhub sample ops file

### ISSUE THREAD

**Issue by patrickhuber** [concourse/concourse-bosh-deployment#40]
I see a vault sample ops file, adding one for credhub will help others set that up as well. 

Here is the sample from my deployment:

```yml
- type: replace
  path: /instance_groups/name=web/jobs/name=atc/properties/credhub?
  value:
    client_id: ((credhub_client_id))
    client_secret: ((credhub_client_secret))
    path_prefix: /concourse
    tls:
      insecure_skip_verify: false
      ca_cert: ((credhub_ca.ca))
    url: https://((credhub_ip)):8844
```
  
Based off of this repo:
https://github.com/nsagoo-pivotal/concourse-credhub-bosh-deployment/blob/master/concourse.yml

And this ops file:
https://github.com/concourse/concourse-deployment/blob/master/cluster/operations/vault-tls-cert-auth.yml

Optionally could use a ((credhub_url)) variable instead of the IP, but the sample comes from a deployment where credhub is on the same VM as the bosh director.
