### ISSUE TITLE
backup-atc.yml does not specify URL/SHA1 for releases entry

### ISSUE THREAD

**Issue by rob-greene** [concourse/concourse-bosh-deployment#77]
The supplied ops file does not supply a URL nor a version, and bosh fails with `Error: Release 'backup-and-restore-sdk' doesn't exist`. I made a local copy and modified with this altered version to get our pipeline deploy to work. I expect the real fix is to update `versions.yml` with a version reference and then reference those variables in the ops file.

```yaml
- type: replace
  path: /releases/name=backup-and-restore-sdk?
  value:
    name: backup-and-restore-sdk
    version: latest
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/backup-and-restore-sdk-release?v=1.9.0"
    sha1: "2f8f805d5e58f72028394af8e750b2a51a432466"
```
